name: copy files
on: [push]

jobs:
  docit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Copy the Readmes
      run: |
        find src/main/resources/ -type f -name "application.example.properties" | while read fname; do
          newname=`echo "$dirname" | sed -e "s/ /_/g"`
          cp "src/main/resources/application.example.properties" "src/main/resources/application.properties"
        done
    - name: Rename files
      run: |
        git mv "src/main/resources/application.example.properties" "src/main/resources/application.properties"